name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
     - 'main'
    
jobs:
  docker-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: docketu.iutnc.univ-lorraine.fr
        username: lopez94u
        password: ${{ secrets.ftp_password }}
